# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  boot.initrd.availableKernelModules =
    [ "ata_piix" "uhci_hcd" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/636a5919-d0f9-44c9-904f-262e24d16161";
    fsType = "xfs";
  };

  fileSystems."/persist/logs" = {
    device = "/dev/disk/by-uuid/9b94dd6b-6dc3-41c4-beaa-969f523be8f7";
    fsType = "xfs";
  };

  fileSystems."/var/log" = {
    device = "/persist/logs";
    fsType = "none";
    options = [ "bind" ];
    neededForBoot = true;
  };

  fileSystems."/var/src/secrets" = {
    device = "/persist/secrets";
    fsType = "none";
    options = [ "bind" ];
    neededForBoot = true;
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/a77c5a4b-6600-47fa-a001-00a1f5592f2e";
    fsType = "ext3";
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/0b9285af-f4a8-462e-99fd-b20a9d8951d4"; }];

  nix.maxJobs = lib.mkDefault 16;
}
