# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  boot.initrd.availableKernelModules =
    [ "ata_piix" "uhci_hcd" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/a820fcb0-79b6-43f1-94a9-3436067b0db2";
    fsType = "xfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/8b9c723e-aeac-4b7b-9346-3ef7eca6a630";
    fsType = "ext2";
  };

  fileSystems."/tmp" = {
    device = "/dev/disk/by-uuid/043e3a8b-711e-4d4e-8340-edc39d8748ac";
    fsType = "xfs";
    neededForBoot = true; # to make sure it gets deleted
  };

  fileSystems."/var/log" = {
    device = "/persist/logs";
    fsType = "none";
    options = [ "bind" ];
    neededForBoot = true;
  };

  fileSystems."/var/src/secrets" = {
    device = "/persist/secrets";
    fsType = "none";
    options = [ "bind" ];
    neededForBoot = true;
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/5931263d-d896-4c98-9b0e-fcef0362941a"; }];

  nix.maxJobs = lib.mkDefault 16;
}
