# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  boot.initrd.availableKernelModules =
    [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/ec88d174-18db-4417-9ed9-a1996a341935";
    fsType = "xfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/78C8-696A";
    fsType = "vfat";
  };

  fileSystems."/var/log" = {
    device = "/persist/logs";
    fsType = "none";
    options = [ "bind" ];
    neededForBoot = true;
  };

  fileSystems."/var/src/secrets" = {
    device = "/persist/secrets";
    fsType = "none";
    options = [ "bind" ];
    neededForBoot = true;
  };

  fileSystems."/persist/secrets" = {
    device = "/dev/disk/by-uuid/c92dc752-e15c-41c2-a92c-fb4dd76b5fb1";
    fsType = "xfs";
    neededForBoot = true;
  };

  fileSystems."/persist/logs" = {
    device = "/dev/disk/by-uuid/d70461d1-6d54-4b94-b320-022c64954284";
    fsType = "xfs";
    neededForBoot = true;
  };

  fileSystems."/persist/data" = {
    device = "/dev/disk/by-uuid/1a39811e-9ce0-409d-ad27-68d4d8f01403";
    fsType = "xfs";
  };

  fileSystems."/persist/intenso" = {
    device = "/dev/disk/by-uuid/aa04b51e-fc5c-4038-9e7b-08bd852de12d";
    fsType = "ext4";
  };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
}
