{
 "title": "Prosody",
 "description": "Prosody stats",
 "tags": [ "Prometheus" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Node",
    "query": "label_values(prosody_stats, job)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "prosody_cpu{type=\"percent\", job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "prosody_memory{job=~\"$job\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Client connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prosody_mod_c2s{job=~\"$job\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Server connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prosody_mod_s2s{job=~\"$job\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Group chats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "prosody_mod_muc", "legendFormat": "{{type}} on {{host}}" }
   ]
  },
  {
   "title": "Client presences",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "prosody_client_presence", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Client identities",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sort_desc(prosody_client_identities)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Client features",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prosody_client_features{type!=\"total\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Stanza counts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    { "expr": "prosody_stanza_counts", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "PEP notification interests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prosody_client_features{type=~\".*notify\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "prosody_client_features{type=\"total\"}",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Message encryption status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    { "expr": "prosody_message_e2ee", "legendFormat": "{{type}}" },
    {
     "expr": "sum(prosody_message_e2ee{type!=\"message\", type!=\"encryption\"})",
     "legendFormat": "Total with text"
    }
   ]
  },
  {
   "title": "Statistics",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "prosody_stats{field=\"average\", job=~\"$job\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "HTTP File Upload",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "prosody_mod_http_upload{field=\"average\", type=\"slot\"}",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "prosody_mod_http_upload{field=\"average\", type=\"upload\"}",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}