# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{

  boot.initrd.availableKernelModules =
    [ "uhci_hcd" "ehci_pci" "hpsa" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/e33988f1-85ef-4bad-a79f-a776e1bd50dc";
    fsType = "xfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/a4a41c48-c97d-4712-a9dd-a7b8dd45323a";
    fsType = "ext2";
  };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/bec3ec49-64b4-49cb-9303-3eace4933aa9"; }];

}
