# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  hardware.cpu.amd.updateMicrocode = true;

  #boot.loader.systemd-boot.enable = true;
  boot.loader.grub.enable = true;
  boot.loader.grub.version = 2;
  boot.loader.grub.device = "/dev/disk/by-id/ata-Samsung_SSD_860_EVO_1TB_S3Z9NB0M344364P";
  boot.loader.grub.useOSProber = true;

  # f2fs support
  boot.supportedFilesystems = [ "xfs" "nfs" "ntfs" ];

  # taken from hardware-configuration.nix
  boot.initrd.availableKernelModules = [
    "ahci"
    "ohci_pci"
    "ehci_pci"
    "pata_jmicron"
    "xhci_pci"
    "firewire_ohci"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.kernelModules = [ "kvm-amd" "amdgpu" ];
  boot.extraModulePackages = [
    config.boot.kernelPackages.acpi_call
    config.boot.kernelPackages.wireguard
  ];

  fileSystems."/" =
    { device = "/dev/disk/by-id/ata-Samsung_SSD_860_EVO_1TB_S3Z9NB0M344364P-part3";
      fsType = "xfs";
    };

  fileSystems."/boot"  = {
    device = "/dev/disk/by-id/ata-Samsung_SSD_860_EVO_1TB_S3Z9NB0M344364P-part1";
    fsType = "ntfs";
  };

  swapDevices = [
    { device = "/dev/disk/by-label/nixos-swap"; }
  ];

  nix.maxJobs = lib.mkDefault 4;

  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";

  boot.consoleLogLevel = 0;
  boot.kernelParams = [ "quiet" "amdgpu.cik_support=1" "amdgpu.si_support=1" ];
}
